### ISSUE TITLE
Unable to run examples: 403 on dataset generation

### ISSUE THREAD

**Issue by ale0xb** [jdfekete/progressivis#5]
Hello,

When running `examples/create_nyc_dataset.sh` I'm getting a 403 error for all resources.
If I enter one of the urls (for example [this one](https://storage.googleapis.com/tlc-trip-data/2015/green_tripdata_2015-01.csv)) I can see more details on the error.

**Comment by xtianpoli** [comment]
Hi Alex,
Thanks for your feedback, the issue is fixed now. Please consider pulling the repository and running the script again.
Best,
Christian

**Comment by ale0xb** [comment]
I can confirm the issue is fixed now. Thanks!
